In [172]:
import chess
import pandas as pd

<font size="5">**ROUND ONE**</font>

**Anand v. Polgar**

In [122]:
ap_game1 = []
with open("tournament - polgar v anand/polgar_v_anand_game1.txt", "r") as f:
    for line in f:
        ap_game1.append(str(line.strip()))

In [123]:
ap_game2 = []
with open("tournament - polgar v anand/polgar_v_anand_game2.txt", "r") as f:
    for line in f:
        ap_game2.append(str(line.strip()))

In [124]:
ap_game3 = []
with open("tournament - polgar v anand/polgar_v_anand_game3.txt", "r") as f:
    for line in f:
        ap_game3.append(str(line.strip()))

In [125]:
ap_game4 = []
with open("tournament - polgar v anand/polgar_v_anand_game4.txt", "r") as f:
    for line in f:
        ap_game4.append(str(line.strip()))

In [126]:
ap_game5 = []
with open("tournament - polgar v anand/polgar_v_anand_game5.txt", "r") as f:
    for line in f:
        ap_game5.append(str(line.strip()))

**Game 1:** Anand

**Game 2:** Polgar

**Game 3:** Anand

**Game 4:** Anand

**Game 5**: Anand

**Caruana v. Kasparov**

In [127]:
ck_game1 = []
with open("tournament - caruana v kasparov/caruana_v_kasparov_game1.txt", "r") as f:
    for line in f:
        ck_game1.append(str(line.strip()))

In [128]:
ck_game2 = []
with open("tournament - caruana v kasparov/caruana_v_kasparov_game2.txt", "r") as f:
    for line in f:
        ck_game2.append(str(line.strip()))

In [129]:
ck_game3 = []
with open("tournament - caruana v kasparov/caruana_v_kasparov_game3.txt", "r") as f:
    for line in f:
        ck_game3.append(str(line.strip()))

In [130]:
ck_game4 = []
with open("tournament - caruana v kasparov/caruana_v_kasparov_game4.txt", "r") as f:
    for line in f:
        ck_game4.append(str(line.strip()))

In [131]:
ck_game5 = []
with open("tournament - caruana v kasparov/caruana_v_kasparov_game5.txt", "r") as f:
    for line in f:
        ck_game5.append(str(line.strip()))

**Game 1:** Caruana

**Game 2:** Kasparov

**Game 3:** Kasparov

**Game 4:** Caruana

**Game 5:** Kasparov

**Nakamura v. Tal**

In [132]:
nt_game1 = []
with open("tournament - nakamura v tal/nakamura_v_tal_game1.txt", "r") as f:
    for line in f:
        nt_game1.append(str(line.strip()))

In [135]:
nt_game2 = []
with open("tournament - nakamura v tal/nakamura_v_tal_game2.txt", "r") as f:
    for line in f:
        nt_game2.append(str(line.strip()))

In [136]:
nt_game3 = []
with open("tournament - nakamura v tal/nakamura_v_tal_game3.txt", "r") as f:
    for line in f:
        nt_game3.append(str(line.strip()))

In [137]:
nt_game4 = []
with open("tournament - nakamura v tal/nakamura_v_tal_game4.txt", "r") as f:
    for line in f:
        nt_game4.append(str(line.strip()))

In [138]:
nt_game5 = []
with open("tournament - nakamura v tal/nakamura_v_tal_game5.txt", "r") as f:
    for line in f:
        nt_game5.append(str(line.strip()))

**Game 1:** Tal

**Game 2:** Nakamura

**Game 3:** Nakamura

**Game 4:** Nakamura

**Game 5:** Tal

**Alekhine v. Carlsen**

In [139]:
ac_game1 = []
with open("tournament - alekhine v carlsen/alekhine_v_carlsen_game1.txt", "r") as f:
    for line in f:
        ac_game1.append(str(line.strip()))

In [140]:
ac_game2 = []
with open("tournament - alekhine v carlsen/alekhine_v_carlsen_game2.txt", "r") as f:
    for line in f:
        ac_game2.append(str(line.strip()))

In [141]:
ac_game3 = []
with open("tournament - alekhine v carlsen/alekhine_v_carlsen_game3.txt", "r") as f:
    for line in f:
        ac_game3.append(str(line.strip()))

In [142]:
ac_game4 = []
with open("tournament - alekhine v carlsen/alekhine_v_carlsen_game4.txt", "r") as f:
    for line in f:
        ac_game4.append(str(line.strip()))

In [144]:
ac_game5 = []
with open("tournament - alekhine v carlsen/alekhine_v_carlsen_game5.txt", "r") as f:
    for line in f:
        ac_game5.append(str(line.strip()))

**Game 1:** Alekhine

**Game 2:** Carlsen

**Game 3:** Carlsen

**Game 4:** Alekhine

**Game 5:** Alekhine

<font size="5">**ROUND TWO**</font>

**Kasparov v. Nakamura**

In [145]:
kn_game1 = []
with open("tournament2 - kasparov v nakamura/kasparov_v_nakamura_game1.txt", "r") as f:
    for line in f:
        kn_game1.append(str(line.strip()))

In [146]:
kn_game2 = []
with open("tournament2 - kasparov v nakamura/kasparov_v_nakamura_game2.txt", "r") as f:
    for line in f:
        kn_game2.append(str(line.strip()))

In [147]:
kn_game3 = []
with open("tournament2 - kasparov v nakamura/kasparov_v_nakamura_game3.txt", "r") as f:
    for line in f:
        kn_game3.append(str(line.strip()))

In [148]:
kn_game4 = []
with open("tournament2 - kasparov v nakamura/kasparov_v_nakamura_game4.txt", "r") as f:
    for line in f:
        kn_game4.append(str(line.strip()))

In [149]:
kn_game5 = []
with open("tournament2 - kasparov v nakamura/kasparov_v_nakamura_game5.txt", "r") as f:
    for line in f:
        kn_game5.append(str(line.strip()))

**Game 1:** Nakamura

**Game 2:** Kasparov

**Game 3:** Nakamura

**Game 4:** Nakamura

**Game 5:** Kasparov

**Anand v. Alekhine**

In [151]:
aa_game1 = []
with open("tournament2 - anand v alekhine/anand_v_alekhine_game1.txt", "r") as f:
    for line in f:
        aa_game1.append(str(line.strip()))

In [152]:
aa_game2 = []
with open("tournament2 - anand v alekhine/anand_v_alekhine_game2.txt", "r") as f:
    for line in f:
        aa_game2.append(str(line.strip()))

In [153]:
aa_game3 = []
with open("tournament2 - anand v alekhine/anand_v_alekhine_game3.txt", "r") as f:
    for line in f:
        aa_game3.append(str(line.strip()))

In [154]:
aa_game4 = []
with open("tournament2 - anand v alekhine/anand_v_alekhine_game4.txt", "r") as f:
    for line in f:
        aa_game4.append(str(line.strip()))

In [155]:
aa_game5 = []
with open("tournament2 - anand v alekhine/anand_v_alekhine_game5.txt", "r") as f:
    for line in f:
        aa_game5.append(str(line.strip()))

**Game 1:** Alekhine

**Game 2:** Alekhine

**Game 3:** Anand

**Game 4:** Alekhine

**Game 5:** Anand

<font size="5">**ROUND THREE**</font>

**Alekhine v. Nakamura**

In [156]:
an_game1 = []
with open("tournament3 - alekhine v nakamura/alekhine_v_nakamura_game1.txt", "r") as f:
    for line in f:
        an_game1.append(str(line.strip()))

In [157]:
an_game2 = []
with open("tournament3 - alekhine v nakamura/alekhine_v_nakamura_game2.txt", "r") as f:
    for line in f:
        an_game2.append(str(line.strip()))

In [158]:
an_game3 = []
with open("tournament3 - alekhine v nakamura/alekhine_v_nakamura_game3.txt", "r") as f:
    for line in f:
        an_game3.append(str(line.strip()))

In [159]:
an_game4 = []
with open("tournament3 - alekhine v nakamura/alekhine_v_nakamura_game4.txt", "r") as f:
    for line in f:
        an_game4.append(str(line.strip()))

In [160]:
an_game5 = []
with open("tournament3 - alekhine v nakamura/alekhine_v_nakamura_game5.txt", "r") as f:
    for line in f:
        an_game5.append(str(line.strip()))

**Game 1:** Nakamura

**Game 2:** Nakamura

**Game 3:** Nakamura

**Game 4:** Nakamura

**Game 5:** Alekhine

In [191]:
def pieces_sacrificed(final_pos):

    black_bishop_count = 0
    black_knight_count = 0
    black_rook_count = 0
    black_queen_count = 0
    black_king_count = 0
    black_pawn_count = 0
    black_sacrificed = 0

    white_bishop_count = 0
    white_knight_count = 0
    white_rook_count = 0
    white_queen_count = 0
    white_king_count = 0
    white_pawn_count = 0
    white_sacrificed = 0

    for piece in final_pos:
        if piece == 'b':
            black_bishop_count += 1
        if piece == 'n':
            black_knight_count +=1
        if piece == 'r':
            black_rook_count += 1
        if piece == 'q':
            black_queen_count +=1
        if piece == 'k':
            black_king_count += 1
        if piece == 'p':
            black_pawn_count += 1


        if piece == 'B':
            white_bishop_count += 1
        if piece == 'N':
            white_knight_count +=1
        if piece == 'R':
            white_rook_count += 1
        if piece == 'Q':
            white_queen_count +=1
        if piece == 'K':
            white_king_count += 1
        if piece == 'P':
            white_pawn_count += 1

    if black_bishop_count == 1:
        black_sacrificed += 1
    if black_bishop_count == 0:
        black_sacrificed += 2
    if black_knight_count == 1:
        black_sacrificed += 1
    if black_knight_count == 0:
        black_sacrificed += 2
    if black_rook_count == 1:
        black_sacrificed += 1
    if black_rook_count == 0:
        black_sacrificed += 2
    if black_queen_count == 0:
        black_sacrificed += 1
    if black_king_count == 0:
        black_sacrificed +=1
    
    if black_pawn_count == 7:
        black_sacrificed += 1
    if black_pawn_count == 6:
        black_sacrificed += 2
    if black_pawn_count == 5:
        black_sacrificed += 3
    if black_pawn_count == 4:
        black_sacrificed += 4
    if black_pawn_count == 3:
        black_sacrificed += 5
    if black_pawn_count == 2:
        black_sacrificed += 6
    if black_pawn_count == 1:
        black_sacrificed += 7
    if black_pawn_count == 0:
        black_sacrificed += 8
        
    if white_bishop_count == 1:
        white_sacrificed += 1
    if white_bishop_count == 0:
        white_sacrificed += 2
    if white_knight_count == 1:
        white_sacrificed += 1
    if white_knight_count == 0:
        white_sacrificed += 2
    if white_rook_count == 1:
        white_sacrificed += 1
    if white_rook_count == 0:
        white_sacrificed += 2
    if white_queen_count == 0:
        white_sacrificed += 1
    if white_king_count == 0:
        white_sacrificed +=1
    
    if white_pawn_count == 7:
        white_sacrificed += 1
    if white_pawn_count == 6:
        white_sacrificed += 2
    if white_pawn_count == 5:
        white_sacrificed += 3
    if white_pawn_count == 4:
        white_sacrificed += 4
    if white_pawn_count == 3:
        white_sacrificed += 5
    if white_pawn_count == 2:
        white_sacrificed += 6
    if white_pawn_count == 1:
        white_sacrificed += 7
    if white_pawn_count == 0:
        white_sacrificed += 8
    total_sac = white_sacrificed + black_sacrificed
    return white_sacrificed, black_sacrificed, total_sac

In [198]:
ap_w_sac1, ap_b_sac1, ap_sac1 = pieces_sacrificed(ap_game1[-1])
ap_w_sac2, ap_b_sac2, ap_sac2 = pieces_sacrificed(ap_game2[-1])
ap_w_sac3, ap_b_sac3, ap_sac3 = pieces_sacrificed(ap_game3[-1])
ap_w_sac4, ap_b_sac4, ap_sac4 = pieces_sacrificed(ap_game4[-1])
ap_w_sac5, ap_b_sac5, ap_sac5 = pieces_sacrificed(ap_game5[-1])

ck_w_sac1, ck_b_sac1, ck_sac1 = pieces_sacrificed(ck_game1[-1])
ck_w_sac2, ck_b_sac2, ck_sac2 = pieces_sacrificed(ck_game2[-1])
ck_w_sac3, ck_b_sac3, ck_sac3 = pieces_sacrificed(ck_game3[-1])
ck_w_sac4, ck_b_sac4, ck_sac4 = pieces_sacrificed(ck_game4[-1])
ck_w_sac5, ck_b_sac5, ck_sac5 = pieces_sacrificed(ck_game5[-1])

nt_w_sac1, nt_b_sac1, nt_sac1 =  pieces_sacrificed(nt_game1[-1])
nt_w_sac2, nt_b_sac2, nt_sac2 =  pieces_sacrificed(nt_game2[-1])
nt_w_sac3, nt_b_sac3, nt_sac3 =  pieces_sacrificed(nt_game3[-1])
nt_w_sac4, nt_b_sac4, nt_sac4 =  pieces_sacrificed(nt_game4[-1])
nt_w_sac5, nt_b_sac5, nt_sac5 =  pieces_sacrificed(nt_game5[-1])

ac_w_sac1, ac_b_sac1, ac_sac1 = pieces_sacrificed(ac_game1[-1])
ac_w_sac2, ac_b_sac2, ac_sac2 = pieces_sacrificed(ac_game2[-1])
ac_w_sac3, ac_b_sac3, ac_sac3 = pieces_sacrificed(ac_game3[-1])
ac_w_sac4, ac_b_sac4, ac_sac4 = pieces_sacrificed(ac_game4[-1])
ac_w_sac5, ac_b_sac5, ac_sac5 = pieces_sacrificed(ac_game5[-1])

kn_w_sac1, kn_b_sac1, kn_sac1 = pieces_sacrificed(kn_game1[-1])
kn_w_sac2, kn_b_sac2, kn_sac2 = pieces_sacrificed(kn_game2[-1])
kn_w_sac3, kn_b_sac3, kn_sac3 = pieces_sacrificed(kn_game3[-1])
kn_w_sac4, kn_b_sac4, kn_sac4 = pieces_sacrificed(kn_game4[-1])
kn_w_sac5, kn_b_sac5, kn_sac5 = pieces_sacrificed(kn_game5[-1])

aa_w_sac1, aa_b_sac1, aa_sac1 = pieces_sacrificed(aa_game1[-1])
aa_w_sac2, aa_b_sac2, aa_sac2 = pieces_sacrificed(aa_game2[-1])
aa_w_sac3, aa_b_sac3, aa_sac3 = pieces_sacrificed(aa_game3[-1])
aa_w_sac4, aa_b_sac4, aa_sac4 = pieces_sacrificed(aa_game4[-1])
aa_w_sac5, aa_b_sac5, aa_sac5 = pieces_sacrificed(aa_game5[-1])

an_w_sac1, an_b_sac1, an_sac1 = pieces_sacrificed(an_game1[-1])
an_w_sac2, an_b_sac2, an_sac2 = pieces_sacrificed(an_game2[-1])
an_w_sac3, an_b_sac3, an_sac3 = pieces_sacrificed(an_game3[-1])
an_w_sac4, an_b_sac4, an_sac4 = pieces_sacrificed(an_game4[-1])
an_w_sac5, an_b_sac5, an_sac5 = pieces_sacrificed(an_game5[-1])

In [215]:
data2 = {'player': ['Polgar', 'Polgar', 'Polgar', 'Polgar', 'Polgar', 'Anand', 'Anand', 'Anand', 'Anand', 'Anand', 
                   'Caruana','Caruana','Caruana','Caruana','Caruana', 'Kasparov','Kasparov','Kasparov','Kasparov',
                    'Kasparov', 'Tal','Tal','Tal','Tal','Tal', 'Nakamura','Nakamura','Nakamura','Nakamura','Nakamura', 
                   'Alekhine','Alekhine','Alekhine','Alekhine','Alekhine','Carlsen','Carlsen','Carlsen','Carlsen',
                    'Carlsen', 'Anand','Anand','Anand','Anand','Anand', 'Alekhine','Alekhine','Alekhine','Alekhine',
                    'Alekhine', 'Kasparov','Kasparov','Kasparov','Kasparov','Kasparov','Nakamura','Nakamura','Nakamura',
                    'Nakamura','Nakamura', 'Alekhine','Alekhine','Alekhine','Alekhine','Alekhine','Nakamura','Nakamura',
                    'Nakamura','Nakamura','Nakamura'],
        'playing': ['White','White','White','White','White', 'Black','Black','Black','Black','Black','White','White',
                    'White','White','White','Black','Black','Black','Black','Black','White','White','White','White',
                    'White', 'Black','Black','Black','Black','Black', 'White','White','White','White','White', 
                    'Black','Black','Black','Black','Black','White','White','White','White','White', 'Black',
                    'Black','Black','Black','Black', 'White','White','White','White','White', 'Black','Black',
                    'Black','Black','Black', 'White','White','White','White','White', 'Black','Black','Black',
                    'Black','Black' ],
        'moves': [len(ap_game1), len(ap_game2), len(ap_game3), len(ap_game4), len(ap_game5), len(ap_game1), 
                  len(ap_game2), len(ap_game3), len(ap_game4), len(ap_game5), len(ck_game1),len(ck_game2),len(ck_game3),
                  len(ck_game4),len(ck_game5), len(ck_game1),len(ck_game2),len(ck_game3),len(ck_game4),len(ck_game5),
                  len(nt_game1),len(nt_game2),len(nt_game3),len(nt_game4),len(nt_game5),len(nt_game1),len(nt_game2),
                  len(nt_game3),len(nt_game4),len(nt_game5), len(ac_game1), len(ac_game2), len(ac_game3), 
                  len(ac_game4), len(ac_game5), len(ac_game1), len(ac_game2), len(ac_game3), len(ac_game4), len(ac_game5),
                  len(aa_game1), len(aa_game2),len(aa_game3),len(aa_game4),len(aa_game5), len(aa_game1),len(aa_game2),
                  len(aa_game3),len(aa_game4),len(aa_game5), len(kn_game1),len(kn_game2),len(kn_game3),len(kn_game4),
                  len(kn_game5), len(kn_game1),len(kn_game2),len(kn_game3), len(kn_game4),len(kn_game5), len(an_game1),
                  len(an_game2),len(an_game3),len(an_game4),len(an_game5), len(an_game1),len(an_game2),len(an_game3),
                  len(an_game4),len(an_game5)],
        'sac_player':[ap_w_sac1,ap_w_sac2,ap_w_sac3,ap_w_sac4,ap_w_sac5,ap_b_sac1, ap_b_sac2, ap_b_sac3, ap_b_sac4,
                      ap_b_sac5, ck_w_sac1,ck_w_sac2,ck_w_sac3,ck_w_sac4,ck_w_sac5, ck_b_sac1,ck_b_sac2,ck_b_sac3,
                      ck_b_sac4,ck_b_sac5,nt_w_sac1, nt_w_sac2,nt_w_sac3,nt_w_sac4,nt_w_sac5, nt_b_sac1,nt_b_sac2,
                      nt_b_sac3,nt_b_sac4,nt_b_sac5,ac_w_sac1,ac_w_sac2,ac_w_sac3,ac_w_sac4,ac_w_sac5,ac_b_sac1, 
                      ac_b_sac2, ac_b_sac3, ac_b_sac4, ac_b_sac5, kn_w_sac1,kn_w_sac2,kn_w_sac3,kn_w_sac4,kn_w_sac5, 
                     kn_b_sac1, kn_b_sac2, kn_b_sac3, kn_b_sac4, kn_b_sac5,aa_w_sac1,aa_w_sac2,aa_w_sac3,aa_w_sac4,
                      aa_w_sac5, aa_b_sac1, aa_b_sac2, aa_b_sac3, aa_b_sac4, aa_b_sac5, an_w_sac1,an_w_sac2,an_w_sac3, 
                      an_w_sac4, an_w_sac5, an_b_sac1,an_b_sac2,an_b_sac3,an_b_sac4,an_b_sac5],
        'sac_game':[ap_sac1,ap_sac2,ap_sac3,ap_sac4,ap_sac5, ap_sac1,ap_sac2,ap_sac3,ap_sac4,ap_sac5,ck_sac1,ck_sac2,
                    ck_sac3,ck_sac4,ck_sac5, ck_sac1,ck_sac2,ck_sac3,ck_sac4,ck_sac5, nt_sac1, nt_sac2,nt_sac3,nt_sac4,
                    nt_sac5, nt_sac1,nt_sac2,nt_sac3,nt_sac4,nt_sac5,ac_sac1,ac_sac2,ac_sac3,ac_sac4,ac_sac5, ac_sac1,
                    ac_sac2,ac_sac3,ac_sac4,ac_sac5,aa_sac1,aa_sac2,aa_sac3,aa_sac4,aa_sac5,aa_sac1,aa_sac2,aa_sac3,aa_sac4,
                    aa_sac5,kn_sac1,kn_sac2,kn_sac3,kn_sac4,kn_sac5,kn_sac1,kn_sac2,kn_sac3,kn_sac4,kn_sac5,an_sac1,an_sac2,
                    an_sac3,an_sac4,an_sac5, an_sac1,an_sac2,an_sac3,an_sac4,an_sac5]}

df = pd.DataFrame(data2)
df.to_csv('models_game_data.csv', index=False)

df

      player playing  moves  sac_player  sac_game
0     Polgar   White     46           4         6
1     Polgar   White     33           2         6
2     Polgar   White     88           6        15
3     Polgar   White     62           8        14
4     Polgar   White     18           2         2
..       ...     ...    ...         ...       ...
65  Nakamura   Black     36           2         6
66  Nakamura   Black     12           0         1
67  Nakamura   Black     48           3         7
68  Nakamura   Black     62           6        11
69  Nakamura   Black     69           3         9

[70 rows x 5 columns]

In [203]:
data = {'White': ['Polgar', 'Polgar', 'Polgar', 'Polgar', 'Polgar', 'Caruana','Caruana','Caruana','Caruana','Caruana',
        'Tal','Tal','Tal','Tal','Tal', 'Alekhine','Alekhine','Alekhine','Alekhine','Alekhine', 'Anand','Anand','Anand',
        'Anand','Anand', 'Kasparov','Kasparov','Kasparov','Kasparov','Kasparov', 'Alekhine','Alekhine','Alekhine',
        'Alekhine','Alekhine'], 'Black': ['Anand', 'Anand', 'Anand', 'Anand', 'Anand', 'Kasparov','Kasparov',
        'Kasparov','Kasparov','Kasparov', 'Nakamura','Nakamura','Nakamura','Nakamura','Nakamura', 'Carlsen','Carlsen',
        'Carlsen','Carlsen','Carlsen', 'Alekhine','Alekhine','Alekhine','Alekhine','Alekhine', 'Nakamura','Nakamura',
        'Nakamura','Nakamura','Nakamura', 'Nakamura','Nakamura','Nakamura','Nakamura','Nakamura'], 'num_moves': 
        [len(ap_game1), len(ap_game2), len(ap_game3), len(ap_game4), len(ap_game5), len(ck_game1),len(ck_game2),
        len(ck_game3),len(ck_game4),len(ck_game5), len(nt_game1),len(nt_game2),len(nt_game3),len(nt_game4),
        len(nt_game5), len(ac_game1), len(ac_game2), len(ac_game3), len(ac_game4), len(ac_game5), len(aa_game1),
         len(aa_game2),len(aa_game3),len(aa_game4),len(aa_game5), len(kn_game1),len(kn_game2),len(kn_game3),
         len(kn_game4),len(kn_game5), len(an_game1),len(an_game2),len(an_game3),len(an_game4),len(an_game5)], 
       'white_sac': [ap_w_sac1,ap_w_sac2,ap_w_sac3,ap_w_sac4,ap_w_sac5,ck_w_sac1,ck_w_sac2,ck_w_sac3,ck_w_sac4,
        ck_w_sac5, nt_w_sac1, nt_w_sac2,nt_w_sac3,nt_w_sac4,nt_w_sac5,ac_w_sac1,ac_w_sac2,ac_w_sac3,ac_w_sac4,
        ac_w_sac5,kn_w_sac1,kn_w_sac2,kn_w_sac3,kn_w_sac4,kn_w_sac5,aa_w_sac1,aa_w_sac2,aa_w_sac3,aa_w_sac4,aa_w_sac5,
        an_w_sac1,an_w_sac2,an_w_sac3, an_w_sac4, an_w_sac5], 'black_sac':[ap_b_sac1, ap_b_sac2, ap_b_sac3, ap_b_sac4,
        ap_b_sac5, ck_b_sac1,ck_b_sac2,ck_b_sac3,ck_b_sac4,ck_b_sac5,nt_b_sac1,nt_b_sac2,nt_b_sac3,nt_b_sac4,nt_b_sac5,
        ac_b_sac1, ac_b_sac2, ac_b_sac3, ac_b_sac4, ac_b_sac5,kn_b_sac1, kn_b_sac2, kn_b_sac3, kn_b_sac4, kn_b_sac5,
        aa_b_sac1, aa_b_sac2, aa_b_sac3, aa_b_sac4, aa_b_sac5,an_b_sac1,an_b_sac2,an_b_sac3,an_b_sac4,an_b_sac5],
        'total_sac': [ap_sac1,ap_sac2,ap_sac3,ap_sac4,ap_sac5,ck_sac1,ck_sac2,ck_sac3,ck_sac4,ck_sac5,nt_sac1,
        nt_sac2,nt_sac3,nt_sac4,nt_sac5,ac_sac1,ac_sac2,ac_sac3,ac_sac4,ac_sac5,kn_sac1,kn_sac2,kn_sac3,kn_sac4,
        kn_sac5,aa_sac1,aa_sac2,aa_sac3,aa_sac4,aa_sac5,an_sac1,an_sac2,an_sac3,an_sac4,an_sac5]}  
  
df = pd.DataFrame(data)  

df.to_csv('models_game_data.csv', index=False)
df

       White     Black  num_moves  white_sac  black_sac  total_sac
0     Polgar     Anand         46          4          2          6
1     Polgar     Anand         33          2          4          6
2     Polgar     Anand         88          6          9         15
3     Polgar     Anand         62          8          6         14
4     Polgar     Anand         18          2          0          2
5    Caruana  Kasparov         79          7          5         12
6    Caruana  Kasparov         30          2          1          3
7    Caruana  Kasparov         66          3          7         10
8    Caruana  Kasparov         87          7          5         12
9    Caruana  Kasparov         86          7          7         14
10       Tal  Nakamura         51          6          7         13
11       Tal  Nakamura         42          4          3          7
12       Tal  Nakamura         78          6          5         11
13       Tal  Nakamura         48          2          3          5
14       Tal  Nakamura         33          3          2          5
15  Alekhine   Carlsen         65          6          8         14
16  Alekhine   Carlsen         70          3          4          7
17  Alekhine   Carlsen         58          4          1          5
18  Alekhine   Carlsen         17          0          1          1
19  Alekhine   Carlsen         45          7          4         11
20     Anand  Alekhine         34          4          6         10
21     Anand  Alekhine         54          2          1          3
22     Anand  Alekhine         47          7          7         14
23     Anand  Alekhine         42          6          5         11
24     Anand  Alekhine         15          2          3          5
25  Kasparov  Nakamura         52          3          2          5
26  Kasparov  Nakamura         45          5          4          9
27  Kasparov  Nakamura         56          3          2          5
28  Kasparov  Nakamura         48          7          3         10
29  Kasparov  Nakamura         51          0          2          2
30  Alekhine  Nakamura         36          4          2          6
31  Alekhine  Nakamura         12          1          0          1
32  Alekhine  Nakamura         48          4          3          7
33  Alekhine  Nakamura         62          5          6         11
34  Alekhine  Nakamura         69          6          3          9